Partially added EventTracking functionality
isc30/blazor-analytics pull request #19
Opened 2020-09-18 21:21 UTC by dinonovak

Hi all,
I am trying to add EventTracking functionality.
I updated typescript and interop definition.

Can you please check if this is working, also what I do not know is how to expose and consume this in blazor app, so please help.

2020-09-18 21:42 UTC, isc30 commented
Hi, thanks for the PR! I will review it tomorrow and try to come up with a
nice way of connecting the component with the rest of the system so the
events can be tracked from anywhere :)

>

2020-09-20 15:50 UTC, isc30 requested changes
Great job! Opened a PR to include injectable support :)
https://github.com/dinonovak/blazor-analytics/pull/1

2020-09-20 21:50 UTC, dinonovak commented
Tested,
so far works great, events are showing up correctly in Google Analytics.

2020-09-21 14:18 UTC, isc30 approved these changes

2020-09-21 14:20 UTC, isc30 approved these changes

2020-09-21 14:20 UTC, merged