Feature/globally disabled tracking
isc30/blazor-analytics pull request #40
Opened 2021-08-05 09:07 UTC by CrahunGit

2021-08-05 16:35 UTC, isc30 requested changes

2021-08-05 16:35 UTC, isc30 commented on README.md
> +```csharp diff
html diff

2021-08-05 16:35 UTC, isc30 commented on README.md
> +```csharp diff
html diff (?)

2021-08-05 16:35 UTC, isc30 commented on src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs
> +            if (!_navigationState.IsTrackingEnabled())
it seems like `global` tracking state shouldn't live in `ITrackingNavigationState` since it also affects events. I would add 2 new functions to `IAnalytics` called `Enable` and `Disable` and track that boolean in here directly.

2021-08-05 16:36 UTC, isc30 commented
Wow, thanks! The overall idea of being able to disable analytics for everything is good, I would implement it directly inside the `IAnalytics` interface since it has nothing to do with Navigation

2021-08-05 16:47 UTC, tlopezface commented on src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs
> +            if (!_navigationState.IsTrackingEnabled())
Yes. It’s better choice to not mix concepts and let the other interface as it is. I’ll implement it.

2021-08-06 07:11 UTC, isc30 approved these changes

2021-08-06 07:12 UTC, merged