Added UserId
isc30/blazor-analytics pull request #52
Opened 2022-03-15 14:51 UTC by jay1891

Hi,

Is it please possible to accept this pull request? It added the UserId, so when a user id is configured it will be added to all page visits and events, and Google Analytics will show more accurate user visits information.

2022-03-15 14:57 UTC, CrahunGit commented on demo/DemoApp/DemoApp.Server/Startup.cs
> +            services.AddGoogleAnalytics("UA-111742878-2");
This your id, isn’t it?

2022-03-15 14:58 UTC, jay1891 commented on demo/DemoApp/DemoApp.Server/Startup.cs
> +            services.AddGoogleAnalytics("UA-111742878-2");
As you can see in your comment, it was removed in the last commit.

2022-03-15 17:35 UTC, isc30 requested changes

2022-03-15 17:35 UTC, isc30 commented on src/Blazor.Analytics/GoogleAnalytics/Resources/GoogleAnalyticsInterop.ts
> +    export function configure(trackingId: string, userId: string, debug: boolean = false): void
can we pass a `Dictionary` with all the props from C# directly and just propagate it to here?

2022-03-15 17:35 UTC, isc30 commented on src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs
> +                GoogleAnalyticsInterop.Configure, _trackingId, _userId, _debug);
pass _extra

2022-03-15 17:35 UTC, isc30 commented on src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs
> +        public async Task ConfigureExtra(string userId)
rename to `AddExtra(string key, string value)` that adds arbitrary values to a dictionary that gets later propagated down to JS

2022-03-15 17:35 UTC, isc30 commented on src/Blazor.Analytics/GoogleAnalytics/Resources/GoogleAnalyticsInterop.ts
> +    export function configure(trackingId: string, userId: string, debug: boolean = false): void
and then do `configObject = Object.assign(configObject, _extra)`

2022-03-15 17:44 UTC, jay1891 commented on src/Blazor.Analytics/GoogleAnalytics/Resources/GoogleAnalyticsInterop.ts
> +    export function configure(trackingId: string, userId: string, debug: boolean = false): void
a problem with not having an explicit user id and a general config object, is that for the event data you don't want there all the config object data also to be added. Giving the option to enable a flexibile config object, allows data to be added to the event data that doesn't belong there.

2022-03-15 17:47 UTC, jay1891 commented on src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs
> +                GoogleAnalyticsInterop.Configure, _trackingId, _userId, _debug);
It is understandable to open the api to have a flexibile config object, but it should then only apply to the gtag("config"...) and the problem is that user id also need to be added to the event data. I tried it but it requires more changes and not only 1 extra dictionary to handle both config and event data.

2022-03-15 17:54 UTC, jay1891 commented on src/Blazor.Analytics/GoogleAnalytics/GoogleAnalyticsStrategy.cs
> +        public async Task ConfigureExtra(string userId)
because there is the "anonymize_ip" pull request, this could be used too with this, but for other things like e.g. cookie data this is then a problem. So opening the API to be able to easily introduces issues, and trying to flatten it all, is I think not a good idea.

2022-03-15 18:30 UTC, jay1891 commented
There is now a global config data & global event data object, hopefully this is helpful?

2022-03-15 22:19 UTC, jay1891 commented
Hi @CrahunGit,

Can you help with the pull request or is it not enough for your standard?

2022-03-16 08:47 UTC, jay1891 commented
Hi @isc30,

Can this be merged?

2022-03-16 08:49 UTC, isc30 commented
At work ATM, I'll review later

2022-03-16 15:59 UTC, isc30 approved these changes
gj, thanks!

2022-03-16 15:59 UTC, merged